export const DEFAULT_CONTENT = {
  en: {
    backgroundColor: '#ffffff',
    useSameFont: true,
    titleFont: 'Inter',
    subtitleFont: 'Inter',
    textFont: 'Inter',
    footerFont: 'Inter',
    useGradient: false,
    titleColor: '#3b82f6',
    subtitleColor: '#60a5fa',
    countdownStyle: 'minimal',
    textColor: '#1a1a1a',
    footerColor: '#4b5563',
    gradientStartColor: '#3b82f6',
    gradientEndColor: '#60a5fa',
    gradientAngle: 45,
    title: 'Welcome to My Landing Page',
    subtitle: 'A beautiful landing page created just for you',
    mainContent: 'This is where your main content goes. Add your message, value proposition, or call to action here.',
    footerText: '© 2025 Your Company. All rights reserved.',
  },
  pt: {
    title: 'Bem-vindo à Minha Página de Destino',
    subtitle: 'Uma bela página de destino criada especialmente para você',
    mainContent: 'É aqui que vai o seu conteúdo principal. Adicione sua mensagem, proposta de valor ou chamada para ação aqui.',
    footerText: '© 2025 Sua Empresa. Todos os direitos reservados.',
  },
  es: {
    title: 'Bienvenido a Mi Página de Destino',
    subtitle: 'Una hermosa página de destino creada especialmente para ti',
    mainContent: 'Aquí es donde va tu contenido principal. Agrega tu mensaje, propuesta de valor o llamada a la acción aquí.',
    footerText: '© 2025 Tu Empresa. Todos los derechos reservados.',
  },
  de: {
    title: 'Willkommen auf Meiner Landingpage',
    subtitle: 'Eine schöne Landingpage, extra für Sie erstellt',
    mainContent: 'Hier kommt Ihr Hauptinhalt hin. Fügen Sie Ihre Botschaft, Ihr Wertversprechen oder Ihren Handlungsaufruf hier ein.',
    footerText: '© 2025 Ihr Unternehmen. Alle Rechte vorbehalten.',
  },
  fr: {
    title: 'Bienvenue sur Ma Page d\'Atterrissage',
    subtitle: 'Une belle page d\'atterrissage créée spécialement pour vous',
    mainContent: 'C\'est ici que va votre contenu principal. Ajoutez votre message, proposition de valeur ou appel à l\'action ici.',
    footerText: '© 2025 Votre Entreprise. Tous droits réservés.',
  },
  zh: {
    title: '欢迎来到我的着陆页',
    subtitle: '为您精心打造的精美着陆页',
    mainContent: '这里是您的主要内容。在此添加您的信息、价值主张或行动号召。',
    footerText: '© 2025 您的公司。保留所有权利。',
  },
  hi: {
    title: 'मेरे लैंडिंग पेज पर आपका स्वागत है',
    subtitle: 'आपके लिए विशेष रूप से बनाया गया एक सुंदर लैंडिंग पेज',
    mainContent: 'यहाँ आपकी मुख्य सामग्री जाती है। अपना संदेश, मूल्य प्रस्ताव या कॉल टू एक्शन यहाँ जोड़ें।',
    footerText: '© 2025 आपकी कंपनी। सर्वाधिकार सुरक्षित।',
  },
  ar: {
    title: 'مرحباً بك في صفحة هبوطي',
    subtitle: 'صفحة هبوط جميلة تم إنشاؤها خصيصاً لك',
    mainContent: 'هنا يذهب المحتوى الرئيسي الخاص بك. أضف رسالتك أو عرض القيمة أو دعوة للعمل هنا.',
    footerText: '© 2025 شركتك. جميع الحقوق محفوظة.',
  },
  bn: {
    title: 'আমার ল্যান্ডিং পেজে স্বাগতম',
    subtitle: 'আপনার জন্য বিশেষভাবে তৈরি একটি সুন্দর ল্যান্ডিং পেজ',
    mainContent: 'এখানে আপনার মূল বিষয়বস্তু যায়। আপনার বার্তা, মূল্য প্রস্তাব বা কল টু অ্যাকশন এখানে যোগ করুন।',
    footerText: '© 2025 আপনার কোম্পানি। সর্বস্বত্ব সংরক্ষিত।',
  },
  ru: {
    title: 'Добро пожаловать на Мою Целевую Страницу',
    subtitle: 'Красивая целевая страница, созданная специально для вас',
    mainContent: 'Здесь размещается ваш основной контент. Добавьте свое сообщение, ценностное предложение или призыв к действию здесь.',
    footerText: '© 2025 Ваша Компания. Все права защищены.',
  },
} as const;